version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rankedpizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/rankedpizza
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
